---
# Defines tasks to install and configure Logwatch

- name: Gather OS specific varibles
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
  tags:
    - common
    - logwatch

- name: Install packages
  action: >
    {{ ansible_pkg_mgr }}
    name="{{ item }}"
    update_cache=yes
    state=latest
  with_items: "{{ logwatch_packages }}"
  tags:
    - common
    - logwatch

- name: Write configuration templates
  template: >
    src=logwatch-conf.j2
    dest="{{ logwatch_config_dir }}/logwatch.conf"
    mode=0644 owner=root group=root
    backup=yes
  tags:
    - common
    - logwatch
